### PR TITLE
WIP: Add Classy binding.

### PR DESCRIPTION
**Pull request by rainwoodman**
This makes classylss.classy a properly installable, full class-code binding.

A few test cases are still failing. I need to ask why.

### CODE REVIEW

**Comment by rainwoodman** [comment]
The default class python binding stinks in several places. But I am not sure if it s a good idea to refactor it given that it's been quite widely used already.

**Comment by rainwoodman** [comment]
I added a largely rewritten binding to classylss.binding. Only Background and Spectra modules are exposed. Should be good enough for LSS? I am not really sure if this is the right place to add an additional class binding or if you plan to deprecate the swig binding at all.

**Comment by nickhand** [comment]
hmm I am not sure. I'll take a look at this next week...wedding is this weekend!

**Comment by rainwoodman** [comment]
Sure! All the best! I think I like the way 'level' is organized here. It's cleaner than the integrated class python binding.

**Comment by rainwoodman** [comment]
I am also tempting to implement/add a python interface to the two phase fluid boltzmann solver described in this post somewhere.
https://arxiv.org/pdf/1605.05283.pdf

This will be useful for neutrino simulations..

**Pull request merged**
