### PR TITLE
fixing travis errors for new classy binding

### PR DESCRIPTION
**Pull request by nickhand**
continuing #10 here

### CODE REVIEW

**Comment by nickhand** [comment]
@rainwoodman this looks great to me....not sure if I want to deprecate the swig binding for now, as it does a few other useful calculations as well. But I think this is ready to merge now?

**Comment by rainwoodman** [comment]
One last thing. 

The units of Class is a bit weird. The power spectrum it returns is in Mpc not in Mpc/h units, though the transfer function produces a k that is in Kpc/h units. I unified them to Mpc/h all the way. What do you think?

**Comment by nickhand** [comment]
Yes I remember that from the C++ library -- I think unifying to h units is the right choice. That is how the C++ library is too. 

I've exposed the sigma8, A_s properties as well now. We might want to think about the ability to set sigma8 directly, which would re-normalize the CLASS outputs properly. That is how the C++ library behaves...

**Comment by rainwoodman** [comment]
- I am not so sure about expose two versions of As.
- If we think of CLASS as a boltzman code then the normalization by a new sigma8 can be done externally in a Python module, not directly via the binding?

**Comment by nickhand** [comment]
Yes I agree with your point about sigma8.

I exposed both because CLASS accepts the normalization in either form, so it's just for convenience. I am happy to remove one of them

**Comment by rainwoodman** [comment]
If class has them then let keep them.

**Comment by rainwoodman** [comment]
I'll merge this PR then.

**Pull request merged**
