### PR TITLE
add docs via readthedocs

### PR DESCRIPTION
**Pull request by nickhand**
addresses #18.

The only caveat is that the API/version of the docs built on RTD will always be the latest conda version due to the fact that we cannot build the package on RTD. So we'll re-build RTD every time the conda package is updated

### CODE REVIEW

**Comment by rainwoodman** [comment]
Could you set it up such that all historical versions of docs are
available? (Also applies to nbodykit..)

**Comment by rainwoodman** [comment]
We are missing a link on the README file.

**Comment by nickhand** [comment]
You can do this manually in RTD by specifying which tagged versions are active, but I am not sure it make sense for classylss. I get around the fact that RTD can't build packages by installing the code via conda from our channel, which will always install the latest version (and RTD doesn't let you customize). So if you build past tagged versions, you'll get the old version of the docs directory from the source code, built against the API from the latest release. So it might be best just to have a single "stable" RTD branch that always points to the latest tagged version.

We can also add a hook to our conda channel to rebuild classylss docs after uploading

**Comment by nickhand** [comment]
Also if you have a RTD username I can add you as a maintainer to these repos

**Comment by rainwoodman** [comment]
It turns out I do. It is rainwoodman.

**Pull request merged**
