### PR TITLE
WIP: Nogcl cosmology

### PR DESCRIPTION
**Pull request by rainwoodman**
This branch implements a Cosmology object based on the class binding here.

There is some effort to normalize the units in class to a Mpc/h system.

When that appeared weird the CLASS units are used. notably offenders are 'hubble_function', 'hubble_function_prime', and 'tau'. But we shall always use 'efunc', 'efunc_prime' (unfortunately a different variable a is used for prime), and conformal_disntance.

The input parameters are class like. The method names are astropy like.

Serialization is supported. Very basic sanity tests are added.

### CODE REVIEW

**Comment by rainwoodman** [comment]
This will replace https://github.com/bccp/nbodykit/pull/365

@nickhand Does this appear to have covered all features we wanted in a cosmology calculator?

We can't go beyond z=0, which may be an issue. Filed as https://github.com/lesgourg/class_public/issues/163 for instructions from class upstream.

**Comment by nickhand** [comment]
This looks good so far to me! Do we want to vectorize the functions? Most take only floats now?

**Comment by rainwoodman** [comment]
I thought most parameters are already vectorized (except species) .. Let me add test cases and figure it out.

**Comment by nickhand** [comment]
I am going to merge this into a "nogcl" branch, then we can both push commits too it

**Pull request merged**
